/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProgressEntry = IDL.Record({
  'id' : IDL.Nat,
  'weight' : IDL.Float64,
  'date' : IDL.Text,
  'notes' : IDL.Text,
  'workoutsCompleted' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProgress' : IDL.Func(
      [IDL.Float64, IDL.Nat, IDL.Text, IDL.Text],
      [ProgressEntry],
      [],
    ),
  'deleteProgress' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'listProgress' : IDL.Func([], [IDL.Vec(ProgressEntry)], ['query']),
  'updateProgress' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProgressEntry = IDL.Record({
    'id' : IDL.Nat,
    'weight' : IDL.Float64,
    'date' : IDL.Text,
    'notes' : IDL.Text,
    'workoutsCompleted' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProgress' : IDL.Func(
        [IDL.Float64, IDL.Nat, IDL.Text, IDL.Text],
        [ProgressEntry],
        [],
      ),
    'deleteProgress' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'listProgress' : IDL.Func([], [IDL.Vec(ProgressEntry)], ['query']),
    'updateProgress' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };